name: gizmo_store
description: "متجر الإلكترونيات الذكي - Gizmo Store"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloudinary_public: ^0.21.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.8.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.3
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  firebase_ui_firestore: ^1.6.5
  firebase_ui_auth: ^1.15.0
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.0.4
  image_picker: ^1.0.4
  firebase_storage: ^12.3.4
  permission_handler: ^11.3.1

dev_dependencies:
  cloudinary_public: ^0.21.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
