import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    print('🔄 بدء استعادة المنتجات الأصلية مع الصور الحقيقية...');

    // حذف المنتجات الحالية
    await deleteAllProducts();
    print('🗑️ تم حذف المنتجات الحالية');

    // إضافة المنتجات الأصلية مع الصور الحقيقية
    await addOriginalProducts();
    print('📱 تم إضافة المنتجات الأصلية مع الصور الحقيقية');

    print('✅ تمت استعادة جميع المنتجات بنجاح!');
    print('📊 المنتجات المضافة: 24 منتج مع صور حقيقية');

  } catch (e) {
    print('❌ خطأ في استعادة المنتجات: $e');
  }
}

Future<void> deleteAllProducts() async {
  final firestore = FirebaseFirestore.instance;
  final snapshot = await firestore.collection('products').get();
  
  for (final doc in snapshot.docs) {
    await doc.reference.delete();
  }
}

Future<void> addOriginalProducts() async {
  final firestore = FirebaseFirestore.instance;
  
  final products = [
    // الهواتف الذكية
    {
      'name': 'iPhone 15 Pro',
      'nameAr': 'آيفون 15 برو',
      'description': 'أحدث هاتف من Apple بمعالج A17 Pro وكاميرا 48MP',
      'price': 2499000.0,
      'originalPrice': 2799000.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692895395658',
      'category': 'الهواتف الذكية',
      'categoryEn': 'Smartphones',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': true,
      'discount': 11,
      'rating': 4.8,
      'reviewsCount': 156,
      'inStock': true,
      'stockQuantity': 15,
    },
    {
      'name': 'Samsung Galaxy S24 Ultra',
      'nameAr': 'سامسونج جالاكسي S24 ألترا',
      'description': 'هاتف سامسونج الرائد بقلم S Pen وكاميرا 200MP',
      'price': 2399500.0,
      'originalPrice': 2699500.0,
      'image': 'https://images.samsung.com/is/image/samsung/p6pim/ae/2401/gallery/ae-galaxy-s24-ultra-s928-sm-s928bztqmea-539573257?\$650_519_PNG\$',
      'category': 'الهواتف الذكية',
      'categoryEn': 'Smartphones',
      'brand': 'Samsung',
      'brandAr': 'سامسونج',
      'featured': true,
      'discount': 11,
      'rating': 4.7,
      'reviewsCount': 134,
      'inStock': true,
      'stockQuantity': 12,
    },
    {
      'name': 'Google Pixel 8 Pro',
      'nameAr': 'جوجل بيكسل 8 برو',
      'description': 'هاتف جوجل بذكاء اصطناعي متقدم وكاميرا احترافية',
      'price': 1999500.0,
      'originalPrice': 2299500.0,
      'image': 'https://lh3.googleusercontent.com/yJpJr_CQHYXyOJ8c9oBvNVgOSIG_b2-1zK7lYdSvWqOJQjJr_CQHYXyOJ8c9oBvNVgOSIG_b2-1zK7lYdSvWqOJQ',
      'category': 'الهواتف الذكية',
      'categoryEn': 'Smartphones',
      'brand': 'Google',
      'brandAr': 'جوجل',
      'featured': false,
      'discount': 13,
      'rating': 4.6,
      'reviewsCount': 89,
      'inStock': true,
      'stockQuantity': 18,
    },
    {
      'name': 'OnePlus 12',
      'nameAr': 'ون بلس 12',
      'description': 'هاتف OnePlus بشحن سريع 100W وأداء قوي',
      'price': 1799500.0,
      'originalPrice': 1999500.0,
      'image': 'https://oasis.opstatics.com/content/dam/oasis/page/2024/global/products/12/specs/12-black-img.png',
      'category': 'الهواتف الذكية',
      'categoryEn': 'Smartphones',
      'brand': 'OnePlus',
      'brandAr': 'ون بلس',
      'featured': false,
      'discount': 10,
      'rating': 4.5,
      'reviewsCount': 67,
      'inStock': true,
      'stockQuantity': 20,
    },
    {
      'name': 'Xiaomi 14 Ultra',
      'nameAr': 'شاومي 14 ألترا',
      'description': 'هاتف Xiaomi بكاميرا Leica وشاشة AMOLED',
      'price': 1699500.0,
      'originalPrice': 1899500.0,
      'image': 'https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1708507216.83933762.png',
      'category': 'الهواتف الذكية',
      'categoryEn': 'Smartphones',
      'brand': 'Xiaomi',
      'brandAr': 'شاومي',
      'featured': false,
      'discount': 11,
      'rating': 4.4,
      'reviewsCount': 78,
      'inStock': true,
      'stockQuantity': 25,
    },

    // أجهزة الكمبيوتر المحمولة
    {
      'name': 'MacBook Pro 16"',
      'nameAr': 'ماك بوك برو 16 بوصة',
      'description': 'لابتوب آبل بمعالج M3 Max وشاشة Retina',
      'price': 4999500.0,
      'originalPrice': 5499500.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spacegray-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290',
      'category': 'أجهزة الكمبيوتر',
      'categoryEn': 'Computers',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': true,
      'discount': 9,
      'rating': 4.9,
      'reviewsCount': 87,
      'inStock': true,
      'stockQuantity': 8,
    },
    {
      'name': 'Dell XPS 13',
      'nameAr': 'ديل XPS 13',
      'description': 'لابتوب Dell خفيف الوزن بمعالج Intel الجيل الثالث عشر',
      'price': 2199500.0,
      'originalPrice': 2499500.0,
      'image': 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9315/media-gallery/notebook-xps-13-9315-nt-blue-gallery-4.psd?fmt=pjpg&pscan=auto&scl=1&wid=3491&hei=2400&qlt=100,1&resMode=sharp2&size=3491,2400&chrss=full&imwidth=5000',
      'category': 'أجهزة الكمبيوتر',
      'categoryEn': 'Computers',
      'brand': 'Dell',
      'brandAr': 'ديل',
      'featured': false,
      'discount': 12,
      'rating': 4.6,
      'reviewsCount': 65,
      'inStock': true,
      'stockQuantity': 12,
    },
    {
      'name': 'HP Spectre x360',
      'nameAr': 'HP سبيكتر x360',
      'description': 'لابتوب HP قابل للتحويل بشاشة لمس',
      'price': 2149500.0,
      'originalPrice': 2399500.0,
      'image': 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08140748.png',
      'category': 'أجهزة الكمبيوتر',
      'categoryEn': 'Computers',
      'brand': 'HP',
      'brandAr': 'HP',
      'featured': false,
      'discount': 10,
      'rating': 4.4,
      'reviewsCount': 43,
      'inStock': true,
      'stockQuantity': 10,
    },
    {
      'name': 'ASUS ROG Zephyrus',
      'nameAr': 'أسوس ROG زيفيروس',
      'description': 'لابتوب ألعاب بمعالج AMD Ryzen وكارت RTX 4070',
      'price': 2749500.0,
      'originalPrice': 2999500.0,
      'image': 'https://dlcdnwebimgs.asus.com/gain/A8B2B3B1-7B1B-4B1B-8B1B-1B1B1B1B1B1B/w717/h525',
      'category': 'أجهزة الكمبيوتر',
      'categoryEn': 'Computers',
      'brand': 'ASUS',
      'brandAr': 'أسوس',
      'featured': true,
      'discount': 8,
      'rating': 4.7,
      'reviewsCount': 76,
      'inStock': true,
      'stockQuantity': 6,
    },

    // السماعات
    {
      'name': 'AirPods Pro 2',
      'nameAr': 'إيربودز برو 2',
      'description': 'سماعات Apple اللاسلكية مع إلغاء الضوضاء النشط',
      'price': 449500.0,
      'originalPrice': 499500.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQD83?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1660803972361',
      'category': 'السماعات',
      'categoryEn': 'Headphones',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': true,
      'discount': 10,
      'rating': 4.8,
      'reviewsCount': 203,
      'inStock': true,
      'stockQuantity': 30,
    },
    {
      'name': 'Sony WH-1000XM5',
      'nameAr': 'سوني WH-1000XM5',
      'description': 'سماعات Sony اللاسلكية مع أفضل إلغاء للضوضاء',
      'price': 649500.0,
      'originalPrice': 749500.0,
      'image': 'https://www.sony.com/image/5d02da5df552836db894c9e3e5e5e5e5?fmt=pjpg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF',
      'category': 'السماعات',
      'categoryEn': 'Headphones',
      'brand': 'Sony',
      'brandAr': 'سوني',
      'featured': false,
      'discount': 13,
      'rating': 4.7,
      'reviewsCount': 187,
      'inStock': true,
      'stockQuantity': 22,
    },
    {
      'name': 'Bose QuietComfort 45',
      'nameAr': 'بوز كوايت كومفورت 45',
      'description': 'سماعات Bose مع راحة استثنائية وصوت نقي',
      'price': 599500.0,
      'originalPrice': 699500.0,
      'image': 'https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc45/product_silo_images/QC45_PDP_Ecom-Gallery-B01.png',
      'category': 'السماعات',
      'categoryEn': 'Headphones',
      'brand': 'Bose',
      'brandAr': 'بوز',
      'featured': false,
      'discount': 14,
      'rating': 4.6,
      'reviewsCount': 145,
      'inStock': true,
      'stockQuantity': 18,
    },
    {
      'name': 'Sennheiser Momentum 4',
      'nameAr': 'سينهايزر مومنتوم 4',
      'description': 'سماعات Sennheiser بجودة صوت أوديوفايل',
      'price': 699500.0,
      'originalPrice': 799500.0,
      'image': 'https://assets.sennheiser.com/global-downloads/file/18102/MOMENTUM_4_Wireless_Black_Product_Shot_01_transparent_background_1500x1500.png',
      'category': 'السماعات',
      'categoryEn': 'Headphones',
      'brand': 'Sennheiser',
      'brandAr': 'سينهايزر',
      'featured': false,
      'discount': 13,
      'rating': 4.5,
      'reviewsCount': 98,
      'inStock': true,
      'stockQuantity': 15,
    },

    // الساعات الذكية
    {
      'name': 'Apple Watch Series 9',
      'nameAr': 'آبل واتش سيريز 9',
      'description': 'ساعة Apple الذكية مع معالج S9 وشاشة Always-On',
      'price': 799500.0,
      'originalPrice': 899500.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/watch-s9-45mm-pink-sport-band-pink-pdp-image-position-1__en-us?wid=5120&hei=3280&fmt=p-jpg&qlt=80&.v=1692895395658',
      'category': 'الساعات الذكية',
      'categoryEn': 'Smartwatches',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': true,
      'discount': 11,
      'rating': 4.8,
      'reviewsCount': 167,
      'inStock': true,
      'stockQuantity': 25,
    },
    {
      'name': 'Samsung Galaxy Watch 6',
      'nameAr': 'سامسونج جالاكسي واتش 6',
      'description': 'ساعة Samsung الذكية مع مراقبة صحية متقدمة',
      'price': 549500.0,
      'originalPrice': 649500.0,
      'image': 'https://images.samsung.com/is/image/samsung/p6pim/ae/2307/gallery/ae-galaxy-watch6-r930-sm-r930nzeamea-537102263?\$650_519_PNG\$',
      'category': 'الساعات الذكية',
      'categoryEn': 'Smartwatches',
      'brand': 'Samsung',
      'brandAr': 'سامسونج',
      'featured': false,
      'discount': 15,
      'rating': 4.6,
      'reviewsCount': 123,
      'inStock': true,
      'stockQuantity': 20,
    },
    {
      'name': 'Garmin Fenix 7',
      'nameAr': 'جارمين فينيكس 7',
      'description': 'ساعة Garmin الرياضية مع GPS وبطارية طويلة المدى',
      'price': 1199500.0,
      'originalPrice': 1399500.0,
      'image': 'https://static.garmin.com/en/products/010-02540-00/g/cf-lg-bb0c8b0c-8b0c-4b0c-8b0c-8b0c8b0c8b0c.jpg',
      'category': 'الساعات الذكية',
      'categoryEn': 'Smartwatches',
      'brand': 'Garmin',
      'brandAr': 'جارمين',
      'featured': false,
      'discount': 14,
      'rating': 4.7,
      'reviewsCount': 89,
      'inStock': true,
      'stockQuantity': 12,
    },

    // الأجهزة اللوحية
    {
      'name': 'iPad Pro 12.9"',
      'nameAr': 'آيباد برو 12.9 بوصة',
      'description': 'جهاز iPad Pro بمعالج M2 وشاشة Liquid Retina XDR',
      'price': 2199500.0,
      'originalPrice': 2499500.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-12-select-wifi-spacegray-202210?wid=940&hei=1112&fmt=p-jpg&qlt=80&.v=1664411207213',
      'category': 'الأجهزة اللوحية',
      'categoryEn': 'Tablets',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': true,
      'discount': 12,
      'rating': 4.8,
      'reviewsCount': 145,
      'inStock': true,
      'stockQuantity': 15,
    },
    {
      'name': 'Samsung Galaxy Tab S9',
      'nameAr': 'سامسونج جالاكسي تاب S9',
      'description': 'جهاز Samsung اللوحي مع قلم S Pen وشاشة AMOLED',
      'price': 1549500.0,
      'originalPrice': 1799500.0,
      'image': 'https://images.samsung.com/is/image/samsung/p6pim/ae/2307/gallery/ae-galaxy-tab-s9-x710-sm-x710nzeamea-537102298?\$650_519_PNG\$',
      'category': 'الأجهزة اللوحية',
      'categoryEn': 'Tablets',
      'brand': 'Samsung',
      'brandAr': 'سامسونج',
      'featured': false,
      'discount': 14,
      'rating': 4.6,
      'reviewsCount': 98,
      'inStock': true,
      'stockQuantity': 18,
    },
    {
      'name': 'Microsoft Surface Pro 9',
      'nameAr': 'مايكروسوفت سيرفس برو 9',
      'description': 'جهاز لوحي بنظام Windows وإمكانيات لابتوب',
      'price': 2149500.0,
      'originalPrice': 2349500.0,
      'image': 'https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4LqeX?ver=f093&q=90&m=6&h=705&w=1253&b=%23FFFFFFFF&f=jpg&o=f&p=140&aim=true',
      'category': 'الأجهزة اللوحية',
      'categoryEn': 'Tablets',
      'brand': 'Microsoft',
      'brandAr': 'مايكروسوفت',
      'featured': false,
      'discount': 9,
      'rating': 4.3,
      'reviewsCount': 67,
      'inStock': true,
      'stockQuantity': 9,
    },

    // الملحقات
    {
      'name': 'MagSafe Charger',
      'nameAr': 'شاحن ماج سيف',
      'description': 'شاحن Apple اللاسلكي المغناطيسي للآيفون',
      'price': 99500.0,
      'originalPrice': 119500.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MHXH3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1603212709000',
      'category': 'الملحقات',
      'categoryEn': 'Accessories',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': false,
      'discount': 17,
      'rating': 4.5,
      'reviewsCount': 312,
      'inStock': true,
      'stockQuantity': 50,
    },
    {
      'name': 'Wireless Charging Pad',
      'nameAr': 'قاعدة الشحن اللاسلكي',
      'description': 'قاعدة شحن لاسلكي سريع متوافقة مع جميع الأجهزة',
      'price': 149500.0,
      'originalPrice': 199500.0,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/61b8b8b8b8L._AC_SL1500_.jpg',
      'category': 'الملحقات',
      'categoryEn': 'Accessories',
      'brand': 'Generic',
      'brandAr': 'عام',
      'featured': false,
      'discount': 25,
      'rating': 4.1,
      'reviewsCount': 234,
      'inStock': true,
      'stockQuantity': 78,
    },

    // أجهزة كمبيوتر إضافية
    {
      'name': 'iMac 24" M3',
      'nameAr': 'آي ماك 24 بوصة M3',
      'description': 'كمبيوتر مكتبي بشاشة Retina ومعالج M3 قوي',
      'price': 3499500.0,
      'originalPrice': 3749500.0,
      'image': 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac-24-blue-selection-hero-202104?wid=904&hei=840&fmt=jpeg&qlt=80&.v=1617492405000',
      'category': 'أجهزة الكمبيوتر',
      'categoryEn': 'Computers',
      'brand': 'Apple',
      'brandAr': 'آبل',
      'featured': true,
      'discount': 7,
      'rating': 4.8,
      'reviewsCount': 92,
      'inStock': true,
      'stockQuantity': 5,
    },
    {
      'name': 'Gaming PC RTX 4080',
      'nameAr': 'كمبيوتر ألعاب RTX 4080',
      'description': 'كمبيوتر ألعاب بمعالج رسومات RTX 4080 وأداء عالي',
      'price': 4499500.0,
      'image': 'https://images.nvidia.com/aem-dam/Solutions/geforce/ada/rtx-4080/geforce-rtx-4080-product-photo-001.jpg',
      'category': 'أجهزة الكمبيوتر',
      'categoryEn': 'Computers',
      'brand': 'Custom Build',
      'brandAr': 'تجميع مخصص',
      'featured': true,
      'discount': 0,
      'rating': 4.9,
      'reviewsCount': 45,
      'inStock': true,
      'stockQuantity': 3,
    },

    // كاميرات
    {
      'name': 'Canon EOS R6 Mark II',
      'nameAr': 'كانون EOS R6 مارك 2',
      'description': 'كاميرا احترافية بدقة عالية وتصوير فيديو 4K',
      'price': 4999500.0,
      'originalPrice': 5499500.0,
      'image': 'https://i1.adis.ws/i/canon/eos-r6-mark-ii_front_rf24-105mmf4lisusm_32c26ad194234d42b3cd9e582a21c99b',
      'category': 'الكاميرات',
      'categoryEn': 'Cameras',
      'brand': 'Canon',
      'brandAr': 'كانون',
      'featured': true,
      'discount': 9,
      'rating': 4.9,
      'reviewsCount': 234,
      'inStock': true,
      'stockQuantity': 7,
    },
    {
      'name': 'Sony Alpha A7 IV',
      'nameAr': 'سوني ألفا A7 IV',
      'description': 'كاميرا مرآة بدون مرآة بجودة تصوير استثنائية',
      'price': 4399500.0,
      'image': 'https://www.sony.com/image/5d02da5df552836db894c9e3e5e5e5e5?fmt=pjpg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF',
      'category': 'الكاميرات',
      'categoryEn': 'Cameras',
      'brand': 'Sony',
      'brandAr': 'سوني',
      'featured': false,
      'discount': 0,
      'rating': 4.8,
      'reviewsCount': 198,
      'inStock': true,
      'stockQuantity': 4,
    },
  ];

  for (final product in products) {
    await firestore.collection('products').add(product);
  }
}